# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: decibel_logger.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'decibel_logger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x65\x63ibel_logger.proto\x12\x0e\x64\x65\x63ibelmonitor\"W\n\x11\x44\x65\x63ibelLogRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x16\n\x0estart_datetime\x18\x02 \x01(\t\x12\x14\n\x0c\x65nd_datetime\x18\x03 \x01(\t\"0\n\x0b\x44\x65\x63ibelData\x12\x10\n\x08\x64\x61tetime\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65\x63ibel\x18\x02 \x01(\x02\"?\n\x12\x44\x65\x63ibelLogResponse\x12)\n\x04logs\x18\x01 \x03(\x0b\x32\x1b.decibelmonitor.DecibelData2g\n\rDecibelLogger\x12V\n\rGetDecibelLog\x12!.decibelmonitor.DecibelLogRequest\x1a\".decibelmonitor.DecibelLogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'decibel_logger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECIBELLOGREQUEST']._serialized_start=40
  _globals['_DECIBELLOGREQUEST']._serialized_end=127
  _globals['_DECIBELDATA']._serialized_start=129
  _globals['_DECIBELDATA']._serialized_end=177
  _globals['_DECIBELLOGRESPONSE']._serialized_start=179
  _globals['_DECIBELLOGRESPONSE']._serialized_end=242
  _globals['_DECIBELLOGGER']._serialized_start=244
  _globals['_DECIBELLOGGER']._serialized_end=347
# @@protoc_insertion_point(module_scope)
